# This rule is not used by the project custom-self-adapter-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the custom-self-adapter.net.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: custom-self-adapter-operator
    app.kubernetes.io/managed-by: kustomize
  name: customselfadapter-editor-role
rules:
- apiGroups:
  - custom-self-adapter.net
  resources:
  - customselfadapters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - custom-self-adapter.net
  resources:
  - customselfadapters/status
  verbs:
  - get
