---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - custom-self-adapter.net
  resources:
  - customselfadapters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - custom-self-adapter.net
  resources:
  - customselfadapters/finalizers
  verbs:
  - update
- apiGroups:
  - custom-self-adapter.net
  resources:
  - customselfadapters/status
  verbs:
  - get
  - patch
  - update
